#!/bin/bash

docker build -t cihm-repomanage . &&
  docker run -it -v $(pwd)/CIHM-Swift:/home/tdr/CIHM-Swift -v $(pwd)/CIHM-TDR:/home/tdr/CIHM-TDR -v "/etc/canadiana/tdr.conf:/home/tdr/tdr.conf" -v "/var/log/tdr:/var/log/tdr" -v "/var/lock/tdr:/var/lock/tdr" -v "/repository:/repository" -v "/cihmz:/cihmz" -v "/cihmz1:/cihmz1" -v "/cihmz2:/cihmz2" cihm-repomanage bash

